// <auto-generated />
using System;
using Accusoft.Api.Data;
using Accusoft.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accusoft.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529100936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "alerta_tipo", new[] { "documento", "envio", "sistema" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "doc_tipo", new[] { "pdf", "docx", "xlsx", "imagem", "arquivo", "outro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "envio_estado", new[] { "pendente", "entregue", "atraso", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "movimentacao_tipo", new[] { "movimentacao_interna", "reposicao_picking", "ajuste", "inventario_parcial", "entrada", "saida" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "admin", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "ativo", "inativo" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accusoft.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Detalhe")
                        .HasColumnType("text")
                        .HasColumnName("detalhe");

                    b.Property<bool>("Lido")
                        .HasColumnType("boolean")
                        .HasColumnName("lido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<AlertaTipo>("Tipo")
                        .HasColumnType("alerta_tipo")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("alertas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Armazem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Morada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("morada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("ResponsavelNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsavel_nome");

                    b.Property<string>("ResponsavelTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("responsavel_telefone");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CriadoPor");

                    b.ToTable("armazens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Atribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ClienteContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente_contacto");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataAtribuicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atribuicao");

                    b.Property<DateTime?>("DataPrevistaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prevista_fim");

                    b.Property<DateTime?>("DataPrevistaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prevista_inicio");

                    b.Property<decimal>("DistanciaTotalKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia_total_km");

                    b.Property<string>("EnderecoDestino")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco_destino");

                    b.Property<string>("EnderecoOrigem")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco_origem");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<string>("NumeroAtribuicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_atribuicao");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TempoEstimadoHoras")
                        .HasColumnType("numeric")
                        .HasColumnName("tempo_estimado_horas");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("integer")
                        .HasColumnName("transportadora_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("atribuicoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.AtribuicaoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtribuicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("atribuicao_id");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Destinatario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destinatario");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<bool>("Realizada")
                        .HasColumnType("boolean")
                        .HasColumnName("realizada");

                    b.HasKey("Id");

                    b.HasIndex("AtribuicaoId");

                    b.ToTable("atribuicao_entregas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acao");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<string>("Detalhe")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhe");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Accusoft.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FromUserId")
                        .HasColumnType("integer")
                        .HasColumnName("from_user_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("Accusoft.Api.Models.ClienteCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("ContactoNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contacto_nome");

                    b.Property<string>("ContactoTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contacto_telefone");

                    b.Property<string>("Contribuinte")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contribuinte");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Localidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidade");

                    b.Property<string>("Morada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("morada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CriadoPor");

                    b.ToTable("clientes_catalogo");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmazemId")
                        .HasColumnType("integer")
                        .HasColumnName("armazem_id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lote");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("QuantidadePicking")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_picking");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_reservada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UltimaMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_movimentacao");

                    b.Property<DateOnly?>("Validade")
                        .HasColumnType("date")
                        .HasColumnName("validade");

                    b.HasKey("Id");

                    b.HasIndex("ArmazemId");

                    b.HasIndex("ProdutoId", "ArmazemId", "Localizacao", "Lote")
                        .IsUnique()
                        .HasDatabaseName("uq_estoque_produto_armazem_local_lote");

                    b.ToTable("estoque");
                });

            modelBuilder.Entity("Accusoft.Api.Models.FornecedorCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("ContactoNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contacto_nome");

                    b.Property<string>("ContactoTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contacto_telefone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Localidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidade");

                    b.Property<string>("Morada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("morada");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CriadoPor");

                    b.ToTable("fornecedores");
                });

            modelBuilder.Entity("Accusoft.Api.Models.GestaoViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CargaDescricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("carga_descricao");

                    b.Property<string>("CargaObservacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("carga_observacoes");

                    b.Property<decimal>("CargaPeso")
                        .HasColumnType("numeric")
                        .HasColumnName("carga_peso");

                    b.Property<int>("CargaVolume")
                        .HasColumnType("integer")
                        .HasColumnName("carga_volume");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFimPlaneada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_planeada");

                    b.Property<DateTime?>("DataFimReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_real");

                    b.Property<DateTime?>("DataInicioPlaneada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_planeada");

                    b.Property<DateTime?>("DataInicioReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_real");

                    b.Property<string>("Destino")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("destino");

                    b.Property<decimal>("DistanciaPercorridaKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia_percorrida_km");

                    b.Property<decimal>("DistanciaTotalKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia_total_km");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<string>("NumeroViagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_viagem");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Origem")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("origem");

                    b.Property<decimal>("PrecoPorKm")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_por_km");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TempoEstimadoHoras")
                        .HasColumnType("numeric")
                        .HasColumnName("tempo_estimado_horas");

                    b.Property<decimal?>("TempoRealHoras")
                        .HasColumnType("numeric")
                        .HasColumnName("tempo_real_horas");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("integer")
                        .HasColumnName("transportadora_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("gestao_viagens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Guia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtribuicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("atribuicao_id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DataEntregaReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrega_real");

                    b.Property<DateTime?>("DataPrevistaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prevista_entrega");

                    b.Property<string>("EnderecoDestino")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco_destino");

                    b.Property<string>("EnderecoOrigem")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco_origem");

                    b.Property<string>("InstrucoesEspeciais")
                        .HasColumnType("text")
                        .HasColumnName("instrucoes_especiais");

                    b.Property<string>("NumeroGuia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_guia");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("PesoTotalKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_total_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<int>("TotalItens")
                        .HasColumnType("integer")
                        .HasColumnName("total_itens");

                    b.Property<int>("TotalVolumes")
                        .HasColumnType("integer")
                        .HasColumnName("total_volumes");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("integer")
                        .HasColumnName("transportadora_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("VolumeTotalM3")
                        .HasColumnType("integer")
                        .HasColumnName("volume_total_m3");

                    b.HasKey("Id");

                    b.HasIndex("AtribuicaoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("guias");
                });

            modelBuilder.Entity("Accusoft.Api.Models.GuiaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuiaId")
                        .HasColumnType("integer")
                        .HasColumnName("guia_id");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lote");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_total");

                    b.Property<decimal>("PesoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("VolumeTotal")
                        .HasColumnType("integer")
                        .HasColumnName("volume_total");

                    b.Property<int>("VolumeUnitario")
                        .HasColumnType("integer")
                        .HasColumnName("volume_unitario");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("guia_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoCorretiva")
                        .HasColumnType("text")
                        .HasColumnName("acao_corretiva");

                    b.Property<int?>("AtribuicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("atribuicao_id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Causa")
                        .HasColumnType("text")
                        .HasColumnName("causa");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal?>("CustoAssociado")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_associado");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ocorrencia");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resolucao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gravidade");

                    b.Property<string>("NumeroIncidente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_incidente");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("ResponsavelResolucao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsavel_resolucao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.Property<int?>("ViagemId")
                        .HasColumnType("integer")
                        .HasColumnName("viagem_id");

                    b.HasKey("Id");

                    b.HasIndex("AtribuicaoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("ViagemId");

                    b.ToTable("incidentes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ClienteContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente_contacto");

                    b.Property<string>("ClienteEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_email");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteMorada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cliente_morada");

                    b.Property<string>("ClienteNif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliente_nif");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataDoc")
                        .HasColumnType("date")
                        .HasColumnName("data_doc");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<decimal?>("HorasTrabalho")
                        .HasColumnType("numeric")
                        .HasColumnName("horas_trabalho");

                    b.Property<string>("MaterialUtilizado")
                        .HasColumnType("text")
                        .HasColumnName("material_utilizado");

                    b.Property<string>("NumeroFatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_fatura");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_url");

                    b.Property<string>("QuemExecutou")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quem_executou");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.Property<int?>("ViagemId")
                        .HasColumnType("integer")
                        .HasColumnName("viagem_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroFatura")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ViagemId");

                    b.ToTable("faturas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer")
                        .HasColumnName("fatura_id");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("fatura_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CartaConducao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("carta_conducao");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<string>("TransportadoraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transportadora_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("motoristas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmazemId")
                        .HasColumnType("integer")
                        .HasColumnName("armazem_id");

                    b.Property<DateTimeOffset>("DataMov")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_mov");

                    b.Property<string>("DestinoLocal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destino_local");

                    b.Property<int?>("EstoqueId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("OrigemLocal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origem_local");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<MovimentacaoTipo>("Tipo")
                        .HasColumnType("movimentacao_tipo")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ArmazemId");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("movimentacoes_estoque");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<int>("Iva")
                        .HasColumnType("integer")
                        .HasColumnName("iva");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("localizacao");

                    b.Property<bool>("LoteObrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("lote_obrigatorio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PesoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_unitario");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("preco_compra");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("preco_venda");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<int>("StockAtual")
                        .HasColumnType("integer")
                        .HasColumnName("stock_atual");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade_medida");

                    b.Property<bool>("ValidadeObrigatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("validade_obrigatoria");

                    b.Property<int>("VolumeUnitario")
                        .HasColumnType("integer")
                        .HasColumnName("volume_unitario");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Recepcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataRecepcao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recepcao");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documento_referencia");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("NumeroRecepcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_recepcao");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TipoEntrada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_entrada");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("rececoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.RecepcaoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Conformidade")
                        .HasColumnType("boolean")
                        .HasColumnName("conformidade");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lote");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("QuantidadeEsperada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_esperada");

                    b.Property<int>("QuantidadeRecebida")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_recebida");

                    b.Property<int>("QuantidadeRejeitada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_rejeitada");

                    b.Property<int>("RecepcaoId")
                        .HasColumnType("integer")
                        .HasColumnName("recepcao_id");

                    b.Property<DateOnly?>("Validade")
                        .HasColumnType("date")
                        .HasColumnName("validade");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RecepcaoId");

                    b.ToTable("recepcao_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTimeOffset>("DataExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenJwt")
                        .HasColumnType("text")
                        .HasColumnName("token_jwt");

                    b.Property<DateTimeOffset>("UltimaAtividade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_atividade");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.TransportadoraCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("ContactoNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contacto_nome");

                    b.Property<string>("ContactoTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contacto_telefone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Localidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidade");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CriadoPor");

                    b.ToTable("transportadoras");
                });

            modelBuilder.Entity("Accusoft.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("CartaConducao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("carta_conducao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("integer")
                        .HasColumnName("transportadora_id");

                    b.Property<DateTimeOffset?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TransportadoraId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("Cilindrada")
                        .HasColumnType("integer")
                        .HasColumnName("cilindrada");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por");

                    b.Property<int?>("Lugares")
                        .HasColumnType("integer")
                        .HasColumnName("lugares");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso");

                    b.Property<int?>("Potencia")
                        .HasColumnType("integer")
                        .HasColumnName("potencia");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("integer")
                        .HasColumnName("proprietario_id");

                    b.Property<string>("TipoCombustivel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_combustivel");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vin");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("veiculos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Alerta", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Armazem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CriadoPorUtilizador");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Atribuicao", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId");

                    b.HasOne("Accusoft.Api.Models.TransportadoraCatalogo", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId");

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId");

                    b.Navigation("Motorista");

                    b.Navigation("Transportadora");

                    b.Navigation("Usuario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Accusoft.Api.Models.AtribuicaoEntrega", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Atribuicao", "Atribuicao")
                        .WithMany("Entregas")
                        .HasForeignKey("AtribuicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atribuicao");
                });

            modelBuilder.Entity("Accusoft.Api.Models.AuditLog", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Accusoft.Api.Models.ChatMessage", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Accusoft.Api.Models.ClienteCatalogo", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CriadoPorUtilizador");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Estoque", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Armazem", "Armazem")
                        .WithMany()
                        .HasForeignKey("ArmazemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armazem");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Accusoft.Api.Models.FornecedorCatalogo", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPorUtilizador");
                });

            modelBuilder.Entity("Accusoft.Api.Models.GestaoViagem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.ClienteCatalogo", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Accusoft.Api.Models.User", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId");

                    b.HasOne("Accusoft.Api.Models.TransportadoraCatalogo", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId");

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId");

                    b.Navigation("Cliente");

                    b.Navigation("Motorista");

                    b.Navigation("Transportadora");

                    b.Navigation("Usuario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Guia", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Atribuicao", "Atribuicao")
                        .WithMany()
                        .HasForeignKey("AtribuicaoId");

                    b.HasOne("Accusoft.Api.Models.ClienteCatalogo", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Accusoft.Api.Models.TransportadoraCatalogo", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId");

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atribuicao");

                    b.Navigation("Cliente");

                    b.Navigation("Transportadora");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.GuiaItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Guia", "Guia")
                        .WithMany("Itens")
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guia");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Incidente", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Atribuicao", "Atribuicao")
                        .WithMany()
                        .HasForeignKey("AtribuicaoId");

                    b.HasOne("Accusoft.Api.Models.ClienteCatalogo", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId");

                    b.HasOne("Accusoft.Api.Models.GestaoViagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("ViagemId");

                    b.Navigation("Atribuicao");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");

                    b.Navigation("Veiculo");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Invoice", b =>
                {
                    b.HasOne("Accusoft.Api.Models.ClienteCatalogo", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.GestaoViagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("Accusoft.Api.Models.InvoiceItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Invoice", "Fatura")
                        .WithMany("Itens")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Motorista", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPorUtilizador");
                });

            modelBuilder.Entity("Accusoft.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Armazem", "Armazem")
                        .WithMany()
                        .HasForeignKey("ArmazemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.Estoque", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId");

                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Armazem");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Produto", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.FornecedorCatalogo", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPorUtilizador");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Recepcao", b =>
                {
                    b.HasOne("Accusoft.Api.Models.FornecedorCatalogo", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.RecepcaoItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Recepcao", "Recepcao")
                        .WithMany("Itens")
                        .HasForeignKey("RecepcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Recepcao");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Sessao", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accusoft.Api.Models.TransportadoraCatalogo", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CriadoPorUtilizador");
                });

            modelBuilder.Entity("Accusoft.Api.Models.User", b =>
                {
                    b.HasOne("Accusoft.Api.Models.TransportadoraCatalogo", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Veiculo", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "CriadoPorUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.ClienteCatalogo", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId");

                    b.Navigation("CriadoPorUtilizador");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Atribuicao", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Guia", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Invoice", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Produto", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Recepcao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.User", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
